/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DnnInfo.h
 *
 * 
 */

#ifndef DnnInfo_H_
#define DnnInfo_H_


#include <string>
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  DnnInfo
{
public:
    DnnInfo();
    virtual ~DnnInfo();

    void validate();

    /////////////////////////////////////////////
    /// DnnInfo members

    /// <summary>
    /// 
    /// </summary>
    std::string getDnn() const;
    void setDnn(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    bool isDefaultDnnIndicator() const;
    void setDefaultDnnIndicator(bool const value);
    bool defaultDnnIndicatorIsSet() const;
    void unsetDefaultDnnIndicator();
    /// <summary>
    /// 
    /// </summary>
    bool isLboRoamingAllowed() const;
    void setLboRoamingAllowed(bool const value);
    bool lboRoamingAllowedIsSet() const;
    void unsetLboRoamingAllowed();
    /// <summary>
    /// 
    /// </summary>
    bool isIwkEpsInd() const;
    void setIwkEpsInd(bool const value);
    bool iwkEpsIndIsSet() const;
    void unsetIwkEpsInd();

    friend void to_json(nlohmann::json& j, const DnnInfo& o);
    friend void from_json(const nlohmann::json& j, DnnInfo& o);
protected:
    std::string m_Dnn;

    bool m_DefaultDnnIndicator;
    bool m_DefaultDnnIndicatorIsSet;
    bool m_LboRoamingAllowed;
    bool m_LboRoamingAllowedIsSet;
    bool m_IwkEpsInd;
    bool m_IwkEpsIndIsSet;
};

}
}
}

#endif /* DnnInfo_H_ */
