/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IdTranslationResult.h
 *
 * 
 */

#ifndef IdTranslationResult_H_
#define IdTranslationResult_H_


#include <string>
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  IdTranslationResult
{
public:
    IdTranslationResult();
    virtual ~IdTranslationResult();

    void validate();

    /////////////////////////////////////////////
    /// IdTranslationResult members

    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();
    /// <summary>
    /// 
    /// </summary>
    std::string getSupi() const;
    void setSupi(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getGpsi() const;
    void setGpsi(std::string const& value);
    bool gpsiIsSet() const;
    void unsetGpsi();

    friend void to_json(nlohmann::json& j, const IdTranslationResult& o);
    friend void from_json(const nlohmann::json& j, IdTranslationResult& o);
protected:
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
    std::string m_Supi;

    std::string m_Gpsi;
    bool m_GpsiIsSet;
};

}
}
}

#endif /* IdTranslationResult_H_ */
