/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IpAddress.h
 *
 * 
 */

#ifndef IpAddress_H_
#define IpAddress_H_


#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  IpAddress
{
public:
    IpAddress();
    virtual ~IpAddress();

    void validate();

    /////////////////////////////////////////////
    /// IpAddress members


    friend void to_json(nlohmann::json& j, const IpAddress& o);
    friend void from_json(const nlohmann::json& j, IpAddress& o);
protected:
};

}
}
}

#endif /* IpAddress_H_ */
