/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Nssai.h
 *
 * 
 */

#ifndef Nssai_H_
#define Nssai_H_


#include <string>
#include "Snssai.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  Nssai
{
public:
    Nssai();
    virtual ~Nssai();

    void validate();

    /////////////////////////////////////////////
    /// Nssai members

    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Snssai>& getDefaultSingleNssais();
        /// <summary>
    /// 
    /// </summary>
    std::vector<Snssai>& getSingleNssais();
    bool singleNssaisIsSet() const;
    void unsetSingleNssais();

    friend void to_json(nlohmann::json& j, const Nssai& o);
    friend void from_json(const nlohmann::json& j, Nssai& o);
protected:
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
    std::vector<Snssai> m_DefaultSingleNssais;

    std::vector<Snssai> m_SingleNssais;
    bool m_SingleNssaisIsSet;
};

}
}
}

#endif /* Nssai_H_ */
