/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PduSessionType.h
 *
 * 
 */

#ifndef PduSessionType_H_
#define PduSessionType_H_


#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>

enum PduSessionType_e {
  PDU_SESSION_TYPE_E_IPV4 = 1,
  PDU_SESSION_TYPE_E_IPV6 = 2,
  PDU_SESSION_TYPE_E_IPV4V6 = 3,
  PDU_SESSION_TYPE_E_UNSTRUCTURED = 4,
  PDU_SESSION_TYPE_E_ETHERNET = 5
};

static const std::vector<std::string> PduSessionTypeStr = {"Error", "IPV4", "IPV6", "IPV4V6", "UNSTRUCTURED", "ETHERNET"};

class  PduSessionType
{
public:
    PduSessionType(PduSessionType_e sessionType): m_sessionType(PduSessionTypeStr[sessionType]) {};
    PduSessionType(std::string sessionType): m_sessionType(sessionType) {};
    PduSessionType();
    virtual ~PduSessionType();

    void validate();

    /////////////////////////////////////////////
    /// PduSessionType members


    friend void to_json(nlohmann::json& j, const PduSessionType& o);
    friend void from_json(const nlohmann::json& j, PduSessionType& o);
protected:
    //PduSessionType_e m_sessionType;
    std::string m_sessionType;
};

}
}
}

#endif /* PduSessionType_H_ */
