/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PduSessionTypes.h
 *
 * 
 */

#ifndef PduSessionTypes_H_
#define PduSessionTypes_H_


#include "PduSessionType.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  PduSessionTypes
{
public:
    PduSessionTypes();
    virtual ~PduSessionTypes();

    void validate();

    /////////////////////////////////////////////
    /// PduSessionTypes members

    /// <summary>
    /// 
    /// </summary>
    PduSessionType getDefaultSessionType() const;
    void setDefaultSessionType(PduSessionType const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<PduSessionType>& getAllowedSessionTypes();
    bool allowedSessionTypesIsSet() const;
    void unsetAllowedSessionTypes();

    friend void to_json(nlohmann::json& j, const PduSessionTypes& o);
    friend void from_json(const nlohmann::json& j, PduSessionTypes& o);
protected:
    PduSessionType m_DefaultSessionType;

    std::vector<PduSessionType> m_AllowedSessionTypes;
    bool m_AllowedSessionTypesIsSet;
};

}
}
}

#endif /* PduSessionTypes_H_ */
