/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SdmSubsModification.h
 *
 * 
 */

#ifndef SdmSubsModification_H_
#define SdmSubsModification_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  SdmSubsModification
{
public:
    SdmSubsModification();
    virtual ~SdmSubsModification();

    void validate();

    /////////////////////////////////////////////
    /// SdmSubsModification members

    /// <summary>
    /// 
    /// </summary>
    std::string getExpires() const;
    void setExpires(std::string const& value);
    bool expiresIsSet() const;
    void unsetExpires();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getMonitoredResourceUris();
    bool monitoredResourceUrisIsSet() const;
    void unsetMonitoredResourceUris();

    friend void to_json(nlohmann::json& j, const SdmSubsModification& o);
    friend void from_json(const nlohmann::json& j, SdmSubsModification& o);
protected:
    std::string m_Expires;
    bool m_ExpiresIsSet;
    std::vector<std::string> m_MonitoredResourceUris;
    bool m_MonitoredResourceUrisIsSet;
};

}
}
}

#endif /* SdmSubsModification_H_ */
