/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SteeringContainer.h
 *
 * 
 */

#ifndef SteeringContainer_H_
#define SteeringContainer_H_


//#include "SecuredPacket.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  SteeringContainer
{
public:
    SteeringContainer();
    virtual ~SteeringContainer();

    void validate();

    /////////////////////////////////////////////
    /// SteeringContainer members


    friend void to_json(nlohmann::json& j, const SteeringContainer& o);
    friend void from_json(const nlohmann::json& j, SteeringContainer& o);
protected:
};

}
}
}

#endif /* SteeringContainer_H_ */
