/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SteeringContainer.h"

namespace oai {
namespace udm {
namespace model {

SteeringContainer::SteeringContainer()
{
    
}

SteeringContainer::~SteeringContainer()
{
}

void SteeringContainer::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const SteeringContainer& o)
{
    j = nlohmann::json();
}

void from_json(const nlohmann::json& j, SteeringContainer& o)
{
}


}
}
}

