/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscribedDefaultQos.h
 *
 * 
 */

#ifndef SubscribedDefaultQos_H_
#define SubscribedDefaultQos_H_


#include "Arp.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscribedDefaultQos
{
public:
    SubscribedDefaultQos();
    virtual ~SubscribedDefaultQos();

    void validate();

    /////////////////////////////////////////////
    /// SubscribedDefaultQos members

    /// <summary>
    /// 
    /// </summary>
    int32_t get5qi() const;
    void set5qi(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    Arp getArp() const;
    void setArp(Arp const& value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getPriorityLevel() const;
    void setPriorityLevel(int32_t const value);
    bool priorityLevelIsSet() const;
    void unsetPriorityLevel();

    friend void to_json(nlohmann::json& j, const SubscribedDefaultQos& o);
    friend void from_json(const nlohmann::json& j, SubscribedDefaultQos& o);
protected:
    int32_t m__5qi;

    Arp m_Arp;

    int32_t m_PriorityLevel;
    bool m_PriorityLevelIsSet;
};

}
}
}

#endif /* SubscribedDefaultQos_H_ */
