/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpuData.h
 *
 * 
 */

#ifndef UpuData_H_
#define UpuData_H_


#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
/// 
/// </summary>
class  UpuData
{
public:
    UpuData();
    virtual ~UpuData();

    void validate();

    /////////////////////////////////////////////
    /// UpuData members


    friend void to_json(nlohmann::json& j, const UpuData& o);
    friend void from_json(const nlohmann::json& j, UpuData& o);
protected:
};

}
}
}

#endif /* UpuData_H_ */
