/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* GPSIToSUPITranslationApiImpl.h
*
* 
*/

#ifndef GPSI_TO_SUPI_TRANSLATION_API_IMPL_H_
#define GPSI_TO_SUPI_TRANSLATION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <GPSIToSUPITranslationApi.h>

#include <pistache/optional.h>

#include "IdTranslationResult.h"
#include "ProblemDetails.h"
#include <string>

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

class GPSIToSUPITranslationApiImpl : public oai::udm::api::GPSIToSUPITranslationApi {
public:
    GPSIToSUPITranslationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~GPSIToSUPITranslationApiImpl() {}

    void get_supi(const std::string &gpsi, const Pistache::Optional<std::string> &supportedFeatures, const Pistache::Optional<Pistache::Http::Header::Raw> &ifNoneMatch, const Pistache::Optional<Pistache::Http::Header::Raw> &ifModifiedSince, Pistache::Http::ResponseWriter &response);

};

}
}
}



#endif