/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* SubscriptionDeletionApiImpl.h
*
* 
*/

#ifndef SUBSCRIPTION_DELETION_API_IMPL_H_
#define SUBSCRIPTION_DELETION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SubscriptionDeletionApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include <string>

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

class SubscriptionDeletionApiImpl : public oai::udm::api::SubscriptionDeletionApi {
public:
    SubscriptionDeletionApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~SubscriptionDeletionApiImpl() {}

    void unsubscribe(const std::string &supi, const std::string &subscriptionId, Pistache::Http::ResponseWriter &response);

};

}
}
}



#endif