/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "SubscriptionModificationApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

SubscriptionModificationApiImpl::SubscriptionModificationApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : SubscriptionModificationApi(rtr)
    { }

void SubscriptionModificationApiImpl::modify(const std::string &supi, const std::string &subscriptionId, const SdmSubsModification &sdmSubsModification, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void SubscriptionModificationApiImpl::modify_shared_data_subs(const std::string &subscriptionId, const SdmSubsModification &sdmSubsModification, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}

