/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* UEContextInSMFDataRetrievalApiImpl.h
*
* 
*/

#ifndef UE_CONTEXT_IN_SMF_DATA_RETRIEVAL_API_IMPL_H_
#define UE_CONTEXT_IN_SMF_DATA_RETRIEVAL_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <UEContextInSMFDataRetrievalApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "UeContextInSmfData.h"
#include <string>

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

class UEContextInSMFDataRetrievalApiImpl : public oai::udm::api::UEContextInSMFDataRetrievalApi {
public:
    UEContextInSMFDataRetrievalApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~UEContextInSMFDataRetrievalApiImpl() {}

    void get_ue_ctx_in_smf_data(const std::string &supi, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response);

};

}
}
}



#endif