/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* AMFRegistrationForNon3GPPAccessApiImpl.h
*
* 
*/

#ifndef AMF_REGISTRATION_FOR_NON3_GPP_ACCESS_API_IMPL_H_
#define AMF_REGISTRATION_FOR_NON3_GPP_ACCESS_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <AMFRegistrationForNon3GPPAccessApi.h>

#include <pistache/optional.h>

#include "AmfNon3GppAccessRegistration.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class AMFRegistrationForNon3GPPAccessApiImpl : public org::openapitools::server::api::AMFRegistrationForNon3GPPAccessApi {
public:
    AMFRegistrationForNon3GPPAccessApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~AMFRegistrationForNon3GPPAccessApiImpl() {}

    void non3_gpp_registration(const std::string &ueId, const AmfNon3GppAccessRegistration &amfNon3GppAccessRegistration, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif