/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * DeleteAuthApiImpl.h
 *
 *
 */

#ifndef DELETE_AUTH_API_IMPL_H_
#define DELETE_AUTH_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <DeleteAuthApi.h>

#include <pistache/optional.h>

#include "AuthEvent.h"
#include "curl.hpp"
#include "logger.hpp"
#include "ProblemDetails.h"
#include "sha256.hpp"
#include <string>
#include "udm_config.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

class DeleteAuthApiImpl : public oai::udm::api::DeleteAuthApi {
public:
  DeleteAuthApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~DeleteAuthApiImpl() {}

  void delete_auth(const std::string &supi, const std::string &authEventId,
                   const AuthEvent &authEvent,
                   Pistache::Http::ResponseWriter &response);
};

} // namespace api
} // namespace udm
} // namespace oai

#endif