/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* PEIUpdateApiImpl.h
*
* 
*/

#ifndef PEI_UPDATE_API_IMPL_H_
#define PEI_UPDATE_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <PEIUpdateApi.h>

#include <pistache/optional.h>

#include "PeiUpdateInfo.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class PEIUpdateApiImpl : public org::openapitools::server::api::PEIUpdateApi {
public:
    PEIUpdateApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~PEIUpdateApiImpl() {}

    void pei_update(const std::string &ueId, const PeiUpdateInfo &peiUpdateInfo, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif