/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* SMFDeregistrationApiImpl.h
*
* 
*/

#ifndef SMF_DEREGISTRATION_API_IMPL_H_
#define SMF_DEREGISTRATION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SMFDeregistrationApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class SMFDeregistrationApiImpl : public org::openapitools::server::api::SMFDeregistrationApi {
public:
    SMFDeregistrationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~SMFDeregistrationApiImpl() {}

    void smf_deregistration(const std::string &ueId, const int32_t &pduSessionId, const Pistache::Optional<std::string> &smfSetId, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif