/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* TriggerAMFFor3GPPAccessDeregistrationApiImpl.h
*
* 
*/

#ifndef TRIGGER_AMF_FOR3_GPP_ACCESS_DEREGISTRATION_API_IMPL_H_
#define TRIGGER_AMF_FOR3_GPP_ACCESS_DEREGISTRATION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <TriggerAMFFor3GPPAccessDeregistrationApi.h>

#include <pistache/optional.h>

#include "AmfDeregInfo.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class TriggerAMFFor3GPPAccessDeregistrationApiImpl : public org::openapitools::server::api::TriggerAMFFor3GPPAccessDeregistrationApi {
public:
    TriggerAMFFor3GPPAccessDeregistrationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~TriggerAMFFor3GPPAccessDeregistrationApiImpl() {}

    void dereg_amf(const std::string &ueId, const AmfDeregInfo &amfDeregInfo, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif