/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* UECMRegistrationInfoRetrievalApiImpl.h
*
* 
*/

#ifndef UECM_REGISTRATION_INFO_RETRIEVAL_API_IMPL_H_
#define UECM_REGISTRATION_INFO_RETRIEVAL_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <UECMRegistrationInfoRetrievalApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "RegistrationDataSetName.h"
#include "RegistrationDataSets.h"
#include "Set.h"
#include "Snssai.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class UECMRegistrationInfoRetrievalApiImpl : public org::openapitools::server::api::UECMRegistrationInfoRetrievalApi {
public:
    UECMRegistrationInfoRetrievalApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~UECMRegistrationInfoRetrievalApiImpl() {}

    void get_registrations(const std::string &ueId, const Pistache::Optional<Set<RegistrationDataSetName>> &registrationDatasetNames, const Pistache::Optional<std::string> &supportedFeatures, const Pistache::Optional<Snssai> &singleNssai, const Pistache::Optional<std::string> &dnn, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif