/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PcscfRestorationNotification.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PcscfRestorationNotification::PcscfRestorationNotification()
{
    m_Supi = "";
    
}

PcscfRestorationNotification::~PcscfRestorationNotification()
{
}

void PcscfRestorationNotification::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const PcscfRestorationNotification& o)
{
    j = nlohmann::json();
    j["supi"] = o.m_Supi;
}

void from_json(const nlohmann::json& j, PcscfRestorationNotification& o)
{
    j.at("supi").get_to(o.m_Supi);
}

std::string PcscfRestorationNotification::getSupi() const
{
    return m_Supi;
}
void PcscfRestorationNotification::setSupi(std::string const& value)
{
    m_Supi = value;
}

}
}
}
}

