/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PeiUpdateInfo.h
 *
 * 
 */

#ifndef PeiUpdateInfo_H_
#define PeiUpdateInfo_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PeiUpdateInfo
{
public:
    PeiUpdateInfo();
    virtual ~PeiUpdateInfo();

    void validate();

    /////////////////////////////////////////////
    /// PeiUpdateInfo members

    /// <summary>
    /// 
    /// </summary>
    std::string getPei() const;
    void setPei(std::string const& value);

    friend void to_json(nlohmann::json& j, const PeiUpdateInfo& o);
    friend void from_json(const nlohmann::json& j, PeiUpdateInfo& o);
protected:
    std::string m_Pei;

};

}
}
}
}

#endif /* PeiUpdateInfo_H_ */
