/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ConfirmAuthApiImpl.h
 *
 *
 */

#ifndef CONFIRM_AUTH_API_IMPL_H_
#define CONFIRM_AUTH_API_IMPL_H_

#include <ConfirmAuthApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <memory>
#include <string>

#include "AuthEvent.h"
#include "ProblemDetails.h"
#include "curl.hpp"
#include "logger.hpp"
#include "sha256.hpp"
#include "udm_config.hpp"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;
using namespace oai::udm::app;

class ConfirmAuthApiImpl : public oai::udm::api::ConfirmAuthApi {
 public:
  ConfirmAuthApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~ConfirmAuthApiImpl() {}

  void confirm_auth(
      const std::string& supi, const AuthEvent& authEvent,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
