/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ConfirmAuthApiImpl.h"
#include "logger.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

ConfirmAuthApiImpl::ConfirmAuthApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
    std::string address)
    : ConfirmAuthApi(rtr) {}

void ConfirmAuthApiImpl::confirm_auth(
    const std::string& supi, const AuthEvent& authEvent,
    Pistache::Http::ResponseWriter& response) {
  Logger::udm_ueau().info("Handle confirm_auth()");

  nlohmann::json confirm_response = {};
  Pistache::Http::Code code       = {};
  uint32_t http_code              = 0;
  std::string location;

  m_udm_app->handle_confirm_auth(
      supi, authEvent, confirm_response, location, http_code);
  code = static_cast<Pistache::Http::Code>(http_code);
  if (code == Pistache::Http::Code::Created) {
    response.headers().add<Pistache::Http::Header::Location>(location);
  }

  // Set content type
  if ((code == Pistache::Http::Code::Created) or
      (code == Pistache::Http::Code::Accepted) or
      (code == Pistache::Http::Code::Ok) or
      (code == Pistache::Http::Code::No_Content)) {
    response.headers().add<Pistache::Http::Header::ContentType>(
        Pistache::Http::Mime::MediaType("application/json"));
  } else {
    response.headers().add<Pistache::Http::Header::ContentType>(
        Pistache::Http::Mime::MediaType("application/problem+json"));
  }

  Logger::udm_ueau().info("Send response to AUSF");
  response.send(code, confirm_response.dump().c_str());
}

}  // namespace api
}  // namespace udm
}  // namespace oai
