/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * CreateEESubscriptionApiImpl.h
 *
 *
 */

#ifndef CREATE_EE_SUBSCRIPTION_API_IMPL_H_
#define CREATE_EE_SUBSCRIPTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <CreateEESubscriptionApi.h>

#include "CreatedEeSubscription.h"
#include "EeSubscription.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::udm::api {

using namespace oai::udm::model;

class CreateEESubscriptionApiImpl
    : public oai::udm::api::CreateEESubscriptionApi {
 public:
  explicit CreateEESubscriptionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~CreateEESubscriptionApiImpl() override = default;

  void create_ee_subscription(
      const std::string& ueIdentity, const EeSubscription& eeSubscription,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::udm::api

#endif
