/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * GenerateAuthDataApiImpl.h
 *
 *
 */

#ifndef GENERATE_AUTH_DATA_API_IMPL_H_
#define GENERATE_AUTH_DATA_API_IMPL_H_

#include <GenerateAuthDataApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "AuthenticationInfoRequest.h"
#include "AuthenticationInfoResult.h"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

class GenerateAuthDataApiImpl : public oai::udm::api::GenerateAuthDataApi {
 public:
  GenerateAuthDataApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~GenerateAuthDataApiImpl() {}

  void generate_auth_data(
      const std::string& supiOrSuci,
      const AuthenticationInfoRequest& authenticationInfoRequest,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
