/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "GenerateAuthDataApiImpl.h"
#include "logger.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::config;
using namespace oai::model::udm;

GenerateAuthDataApiImpl::GenerateAuthDataApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
    std::string address)
    : GenerateAuthDataApi(rtr) {}

void GenerateAuthDataApiImpl::generate_auth_data(
    const std::string& supiOrSuci,
    const AuthenticationInfoRequest& authenticationInfoRequest,
    Pistache::Http::ResponseWriter& response) {
  Logger::udm_ueau().info("Handle generate_auth_data()");

  std::string reponse_from_udr;
  nlohmann::json auth_info_response = {};
  Pistache::Http::Code code         = {};
  uint32_t http_code                = 0;

  m_udm_app->handle_generate_auth_data_request(
      supiOrSuci, authenticationInfoRequest, auth_info_response, http_code);

  code = static_cast<Pistache::Http::Code>(http_code);

  // Set content type
  if ((code == Pistache::Http::Code::Created) or
      (code == Pistache::Http::Code::Accepted) or
      (code == Pistache::Http::Code::Ok) or
      (code == Pistache::Http::Code::No_Content)) {
    response.headers().add<Pistache::Http::Header::ContentType>(
        Pistache::Http::Mime::MediaType("application/json"));
  } else {
    response.headers().add<Pistache::Http::Header::ContentType>(
        Pistache::Http::Mime::MediaType("application/problem+json"));
  }

  Logger::udm_ueau().info("Send response to AUSF");
  response.send(code, auth_info_response.dump().c_str());

  Logger::udm_ueau().info("Update sqn in Database");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
