/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IPSMGWDeregistrationApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;
IPSMGWDeregistrationApiImpl::IPSMGWDeregistrationApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr)
    : IPSMGWDeregistrationApi(rtr) {}

void IPSMGWDeregistrationApiImpl::ip_sm_gw_deregistration(
    const std::string& ueId, Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
