/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IPSMGWRegistrationInfoRetrievalApiImpl.h
 *
 *
 */

#ifndef IPSMGW_REGISTRATION_INFO_RETRIEVAL_API_IMPL_H_
#define IPSMGW_REGISTRATION_INFO_RETRIEVAL_API_IMPL_H_

#include <IPSMGWRegistrationInfoRetrievalApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <memory>
#include <string>

#include "IpSmGwRegistration.h"
#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class IPSMGWRegistrationInfoRetrievalApiImpl
    : public org::openapitools::server::api::
          IPSMGWRegistrationInfoRetrievalApi {
 public:
  IPSMGWRegistrationInfoRetrievalApiImpl(
      std::shared_ptr<Pistache::Rest::Router>);
  ~IPSMGWRegistrationInfoRetrievalApiImpl() {}

  void get_ip_sm_gw_registration(
      const std::string& ueId, Pistache::Http::ResponseWriter& response);
};

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif