/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IPSMGWRegistrationApiImpl.h
 *
 *
 */

#ifndef IPSMGW_REGISTRATION_API_IMPL_H_
#define IPSMGW_REGISTRATION_API_IMPL_H_

#include <IPSMGWRegistrationApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <memory>
#include <string>

#include "IpSmGwRegistration.h"
#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;
class IPSMGWRegistrationApiImpl : public oai::udm::api::IPSMGWRegistrationApi {
 public:
  IPSMGWRegistrationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~IPSMGWRegistrationApiImpl() {}

  void ip_sm_gw_registration(const std::string& ueId,
                             const IpSmGwRegistration& ipSmGwRegistration,
                             Pistache::Http::ResponseWriter& response);
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
