/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl.h
 *
 *
 */

#ifndef PARAMETER_UPDATE_IN_THE_AMF_REGISTRATION_FOR3_GPP_ACCESS_API_IMPL_H_
#define PARAMETER_UPDATE_IN_THE_AMF_REGISTRATION_FOR3_GPP_ACCESS_API_IMPL_H_

#include <ParameterUpdateInTheAMFRegistrationFor3GPPAccessApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "Amf3GppAccessRegistrationModification.h"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

class ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl
    : public oai::udm::api::
          ParameterUpdateInTheAMFRegistrationFor3GPPAccessApi {
 public:
  ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl() {}

  void update3_gpp_registration(
      const std::string& ueId,
      const Amf3GppAccessRegistrationModification&
          amf3GppAccessRegistrationModification,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
