/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl.h
*
* 
*/

#ifndef PARAMETER_UPDATE_IN_THE_AMF_REGISTRATION_FOR3_GPP_ACCESS_API_IMPL_H_
#define PARAMETER_UPDATE_IN_THE_AMF_REGISTRATION_FOR3_GPP_ACCESS_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ParameterUpdateInTheAMFRegistrationFor3GPPAccessApi.h>

#include <pistache/optional.h>

#include "Amf3GppAccessRegistrationModification.h"
#include "PatchResult.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl : public org::openapitools::server::api::ParameterUpdateInTheAMFRegistrationFor3GPPAccessApi {
public:
    ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl() {}

    void update3_gpp_registration(const std::string &ueId, const Amf3GppAccessRegistrationModification &amf3GppAccessRegistrationModification, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif