/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl::
    ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
        std::string address)
    : ParameterUpdateInTheAMFRegistrationFor3GPPAccessApi(rtr) {}

void ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl::
    update3_gpp_registration(
        const std::string& ueId,
        const Amf3GppAccessRegistrationModification&
            amf3GppAccessRegistrationModification,
        const Pistache::Optional<std::string>& supportedFeatures,
        Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok,
      "ParameterUpdateInTheAMFRegistrationFor3GPPAccessApiImpl::update3_gpp_"
      "registrationAPI has not been implemented yet!\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
