/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PEIUpdateApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;

PEIUpdateApiImpl::PEIUpdateApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
    std::string address)
    : PEIUpdateApi(rtr) {}

void PEIUpdateApiImpl::pei_update(
    const std::string& ueId, const PeiUpdateInfo& peiUpdateInfo,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok,
      "PEIUpdateApiImpl::pei_update API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
