/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "RetrievalOfSharedDataApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

RetrievalOfSharedDataApiImpl::RetrievalOfSharedDataApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
    std::string address)
    : RetrievalOfSharedDataApi(rtr) {}

void RetrievalOfSharedDataApiImpl::get_shared_data(
    const Pistache::Optional<std::vector<std::string>>& sharedDataIds,
    const Pistache::Optional<std::string>& supportedFeatures,
    const Pistache::Optional<Pistache::Http::Header::Raw>& ifNoneMatch,
    const Pistache::Optional<Pistache::Http::Header::Raw>& ifModifiedSince,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok,
      "RetrievalOfSharedDataApiImpl::get_shared_data API has not been "
      "implemented yet!\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
