/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "RetrievalOfMultipleDataSetsApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::_3gpp::model;
using namespace oai::udm::app;

RetrievalOfMultipleDataSetsApiImpl::RetrievalOfMultipleDataSetsApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
    std::string address)
    : RetrievalOfMultipleDataSetsApi(rtr),
      m_udm_app(udm_app_inst),
      m_address(address) {}

void RetrievalOfMultipleDataSetsApiImpl::get_data_sets(
    const std::string& supi,
    const std::optional<std::vector<std::string>>& datasetNames,
    const std::optional<PlmnId>& plmnId,
    const std::optional<std::string>& supportedFeatures,
    const std::optional<Pistache::Http::Header::Raw>& ifNoneMatch,
    const std::optional<Pistache::Http::Header::Raw>& ifModifiedSince,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok,
      "RetrievalOfMultipleDataSetsApiImpl::get_data_sets API has not been "
      "implemented yet!\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
