/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SessionManagementSubscriptionDataRetrievalApiImpl.h
 *
 *
 */

#ifndef SESSION_MANAGEMENT_SUBSCRIPTION_DATA_RETRIEVAL_API_IMPL_H_
#define SESSION_MANAGEMENT_SUBSCRIPTION_DATA_RETRIEVAL_API_IMPL_H_

#include <SessionManagementSubscriptionDataRetrievalApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <optional>
#include <pistache/router.h>

#include "PlmnId.h"
#include "SessionManagementSubscriptionData.h"
#include "Snssai.h"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::app;

class SessionManagementSubscriptionDataRetrievalApiImpl
    : public oai::udm::api::SessionManagementSubscriptionDataRetrievalApi {
 public:
  SessionManagementSubscriptionDataRetrievalApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~SessionManagementSubscriptionDataRetrievalApiImpl() {}

  // void get_sm_data(const std::string &supi, const
  // std::optional<std::string> &supportedFeatures, const
  // std::optional<Snssai> &singleNssai, const
  // std::optional<std::string> &dnn, const std::optional<PlmnId>
  // &plmnId, const std::optional<Pistache::Http::Header::Raw>
  // &ifNoneMatch, const std::optional<Pistache::Http::Header::Raw>
  // &ifModifiedSince, Pistache::Http::ResponseWriter &response);
  void get_sm_data(
      const std::string& supi,
      const std::optional<oai::_3gpp::model::Snssai>& singleNssai,
      const std::optional<std::string>& dnn,
      const std::optional<oai::_3gpp::model::PlmnId>& plmnId,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
