/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SMFSmfRegistrationApiImpl.h
 *
 *
 */

#ifndef SMF_SMF_REGISTRATION_API_IMPL_H_
#define SMF_SMF_REGISTRATION_API_IMPL_H_

#include <SMFSmfRegistrationApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <memory>
#include <string>

#include "ProblemDetails.h"
#include "SmfRegistration.h"
#include "SmfRegistrationInfo.h"
#include "Snssai.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;
class SMFSmfRegistrationApiImpl : public oai::udm::api::SMFSmfRegistrationApi {
 public:
  SMFSmfRegistrationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~SMFSmfRegistrationApiImpl() {}

  void get_smf_registration(
      const std::string& ueId, const Pistache::Optional<Snssai>& singleNssai,
      const Pistache::Optional<std::string>& dnn,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);
  void registration(const std::string& ueId, const int32_t& pduSessionId,
                    const SmfRegistration& smfRegistration,
                    Pistache::Http::ResponseWriter& response);
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
