/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SMSFDeregistrationFor3GPPAccessApiImpl.h
 *
 *
 */

#ifndef SMSF_DEREGISTRATION_FOR3_GPP_ACCESS_API_IMPL_H_
#define SMSF_DEREGISTRATION_FOR3_GPP_ACCESS_API_IMPL_H_

#include <SMSFDeregistrationFor3GPPAccessApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <memory>
#include <string>

#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;
class SMSFDeregistrationFor3GPPAccessApiImpl
    : public oai::udm::api::SMSFDeregistrationFor3GPPAccessApi {
 public:
  SMSFDeregistrationFor3GPPAccessApiImpl(
      std::shared_ptr<Pistache::Rest::Router>);
  ~SMSFDeregistrationFor3GPPAccessApiImpl() {}

  void _3_gpp_smsf_deregistration(
      const std::string& ueId, const Pistache::Optional<std::string>& smsfSetId,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
