/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SMSF3GPPAccessRegistrationInfoRetrievalApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;
SMSF3GPPAccessRegistrationInfoRetrievalApiImpl::
    SMSF3GPPAccessRegistrationInfoRetrievalApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr)
    : SMSF3GPPAccessRegistrationInfoRetrievalApi(rtr) {}

void SMSF3GPPAccessRegistrationInfoRetrievalApiImpl::get3_gpp_smsf_registration(
    const std::string& ueId,
    const Pistache::Optional<std::string>& supportedFeatures,
    Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
