/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SMSFDeregistrationForNon3GPPAccessApiImpl.h
 *
 *
 */

#ifndef SMSF_DEREGISTRATION_FOR_NON3_GPP_ACCESS_API_IMPL_H_
#define SMSF_DEREGISTRATION_FOR_NON3_GPP_ACCESS_API_IMPL_H_

#include <SMSFDeregistrationForNon3GPPAccessApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <memory>
#include <string>

#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class SMSFDeregistrationForNon3GPPAccessApiImpl
    : public org::openapitools::server::api::
          SMSFDeregistrationForNon3GPPAccessApi {
 public:
  SMSFDeregistrationForNon3GPPAccessApiImpl(
      std::shared_ptr<Pistache::Rest::Router>);
  ~SMSFDeregistrationForNon3GPPAccessApiImpl() {}

  void non3_gpp_smsf_deregistration(
      const std::string& ueId, const Pistache::Optional<std::string>& smsfSetId,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif