/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SMSF3GPPAccessRegistrationInfoRetrievalApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

SMSF3GPPAccessRegistrationInfoRetrievalApiImpl::
    SMSF3GPPAccessRegistrationInfoRetrievalApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr, udm_app* udm_app_inst,
        std::string address)
    : SMSF3GPPAccessRegistrationInfoRetrievalApi(rtr) {}

void SMSF3GPPAccessRegistrationInfoRetrievalApiImpl::get3_gpp_smsf_registration(
    const std::string& ueId,
    const Pistache::Optional<std::string>& supportedFeatures,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok,
      "SMSF3GPPAccessRegistrationInfoRetrievalApiImpl::get3_gpp_smsf_"
      "registration API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
