/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SMSFRegistrationForNon3GPPAccessApiImpl.h
 *
 *
 */

#ifndef SMSF_REGISTRATION_FOR_NON3_GPP_ACCESS_API_IMPL_H_
#define SMSF_REGISTRATION_FOR_NON3_GPP_ACCESS_API_IMPL_H_

#include <SMSFRegistrationForNon3GPPAccessApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "SmsfRegistration.h"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;
using namespace oai::udm::app;

class SMSFRegistrationForNon3GPPAccessApiImpl
    : public oai::udm::api::SMSFRegistrationForNon3GPPAccessApi {
 public:
  SMSFRegistrationForNon3GPPAccessApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~SMSFRegistrationForNon3GPPAccessApiImpl() {}

  void non3_gpp_smsf_registration(
      const std::string& ueId, const SmsfRegistration& smsfRegistration,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
