/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SMSManagementSubscriptionDataRetrievalApiImpl.h
 *
 *
 */

#ifndef SMS_MANAGEMENT_SUBSCRIPTION_DATA_RETRIEVAL_API_IMPL_H_
#define SMS_MANAGEMENT_SUBSCRIPTION_DATA_RETRIEVAL_API_IMPL_H_

#include <SMSManagementSubscriptionDataRetrievalApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "PlmnId.h"
#include "SmsManagementSubscriptionData.h"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::app;

class SMSManagementSubscriptionDataRetrievalApiImpl
    : public oai::udm::api::SMSManagementSubscriptionDataRetrievalApi {
 public:
  SMSManagementSubscriptionDataRetrievalApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~SMSManagementSubscriptionDataRetrievalApiImpl() {}

  void get_sms_mngt_data(
      const std::string& supi,
      const Pistache::Optional<std::string>& supportedFeatures,
      const Pistache::Optional<oai::model::common::PlmnId>& plmnId,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifNoneMatch,
      const Pistache::Optional<Pistache::Http::Header::Raw>& ifModifiedSince,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
