/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "TriggerPCSCFRestorationApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

TriggerPCSCFRestorationApiImpl::TriggerPCSCFRestorationApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : TriggerPCSCFRestorationApi(rtr)
    { }

void TriggerPCSCFRestorationApiImpl::trigger_pcscf_restoration(const TriggerRequest &triggerRequest, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

