/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * UECMRegistrationInfoRetrievalApiImpl.h
 *
 *
 */

#ifndef UECM_REGISTRATION_INFO_RETRIEVAL_API_IMPL_H_
#define UECM_REGISTRATION_INFO_RETRIEVAL_API_IMPL_H_

#include <UECMRegistrationInfoRetrievalApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <optional>
#include <pistache/router.h>

#include "RegistrationDataSetName.h"
#include "RegistrationDataSets.h"
#include "Snssai.h"
#include "udm_app.hpp"

namespace oai {
namespace udm {
namespace api {

using namespace oai::_3gpp::model;
using namespace oai::udm::app;

class UECMRegistrationInfoRetrievalApiImpl
    : public oai::udm::api::UECMRegistrationInfoRetrievalApi {
 public:
  UECMRegistrationInfoRetrievalApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, udm_app* udm_app_inst,
      std::string address);
  ~UECMRegistrationInfoRetrievalApiImpl() {}

  // void get_registrations(const std::string &ueId, const
  // std::optional<Set<RegistrationDataSetName>> &registrationDatasetNames,
  // const std::optional<std::string> &supportedFeatures, const
  // std::optional<Snssai> &singleNssai, const
  // std::optional<std::string> &dnn, Pistache::Http::ResponseWriter
  // &response);
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif
