/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * UpdateEESubscriptionApiImpl.h
 *
 *
 */

#ifndef UPDATE_EE_SUBSCRIPTION_API_IMPL_H_
#define UPDATE_EE_SUBSCRIPTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <UpdateEESubscriptionApi.h>

#include "PatchItem.h"
#include "PatchResult.h"
#include "ProblemDetails.h"
#include "udm_app.hpp"
#include <string>
#include <vector>

namespace oai::udm::api {

using namespace oai::udm::app;

class UpdateEESubscriptionApiImpl
    : public oai::udm::api::UpdateEESubscriptionApi {
 public:
  explicit UpdateEESubscriptionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr, udm_app* udm_app_inst,
      std::string address);
  ~UpdateEESubscriptionApiImpl() override = default;

  void update_ee_subscription(
      const std::string& ueIdentity, const std::string& subscriptionId,
      const std::vector<oai::model::common::PatchItem>& patchItem,
      const std::optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace oai::udm::api

#endif
