/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UpdateEESubscriptionApiImpl.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

UpdateEESubscriptionApiImpl::UpdateEESubscriptionApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : UpdateEESubscriptionApi(rtr) {}

void UpdateEESubscriptionApiImpl::update_ee_subscription(
    const std::string& ueIdentity, const std::string& subscriptionId,
    const std::vector<PatchItem>& patchItem,
    const std::optional<std::string>& supportedFeatures,
    Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace udm
}  // namespace oai
