## UDM configuration file
UDM = 
{
  INSTANCE_ID = 10;
  PID_DIRECTORY = "/var/run";

  UDM_NAME = "OAI-UDM";

  INTERFACES:{
    # UDM binded interface for SBI interface (e.g., communication with UDR, AUSF)
    SBI:{
        INTERFACE_NAME = "eno1";                #interface for providing udm service
        IPV4_ADDRESS   = "192.168.199.222/24";  #address for intercafe (cidr)
        PORT           = 8181;                  #udm service port 
        PPID           = 60;
    };
  };
  
  NUDR:{
        INTERFACE_NAME = "eno1";                #interface for request for udr service
        IPV4_ADDRESS   = "192.168.199.222/24";  #udr address (cidr)
        PORT           = 8080;                  #udr port
        VERSION        = "v2"; 
    };

};


