## udm configuration file
UDM = 
{
  INSTANCE_ID = 10;
  PID_DIRECTORY = "/var/run";

  UDM_NAME = "bupt-amf";

  INTERFACES:{
    SBI_UDM:{
        INTERFACE_NAME = "ens32";               #interface for providing udm service
        IPV4_ADDRESS   = "192.168.2.35/24";   #address for intercafe (cidr)
        PORT           = 8181;                  #udm service port 
        PPID           = 60;
    };
    NUDR:{
        INTERFACE_NAME = "ens32";               #interface for request for udr service
        IPV4_ADDRESS   = "192.168.2.35/24";  #udr address (cidr)
        PORT           = 8080;                  #udr port
        VERSION        = "v2"; 
    };
  };

};


