/**
 * RNI API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
 *
 * OpenAPI spec version: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 *file except in compliance with the License. You may obtain a copy of the
 *License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

#ifndef FILE_UDM_API_SERVER_SEEN
#define FILE_UDM_API_SERVER_SEEN

#include "pistache/endpoint.h"
#include "pistache/http.h"
#include "pistache/router.h"
#ifdef __linux__
#include <vector>
#include <signal.h>
#include <unistd.h>
#endif

#include "AccessAndMobilitySubscriptionDataRetrievalApiImpl.h"
#include "GPSIToSUPITranslationApiImpl.h"
#include "GroupIdentifiersApiImpl.h"
#include "ProvidingAcknowledgementOfSteeringOfRoamingApiImpl.h"
#include "ProvidingAcknowledgementOfUEParametersUpdateApiImpl.h"
#include "RetrievalOfMultipleDataSetsApiImpl.h"
#include "RetrievalOfSharedDataApiImpl.h"
#include "SMFSelectionSubscriptionDataRetrievalApiImpl.h"
#include "SMSManagementSubscriptionDataRetrievalApiImpl.h"
#include "SMSSubscriptionDataRetrievalApiImpl.h"
#include "SessionManagementSubscriptionDataRetrievalApiImpl.h"
#include "SliceSelectionSubscriptionDataRetrievalApiImpl.h"
#include "SubscriptionCreationApiImpl.h"
#include "SubscriptionCreationForSharedDataApiImpl.h"
#include "SubscriptionDeletionApiImpl.h"
#include "SubscriptionDeletionForSharedDataApiImpl.h"
#include "SubscriptionModificationApiImpl.h"
#include "TraceConfigurationDataRetrievalApiImpl.h"
#include "UEContextInSMFDataRetrievalApiImpl.h"
#include "UEContextInSMSFDataRetrievalApiImpl.h"

#include "ConfirmAuthApiImpl.h"
#include "DeleteAuthApiImpl.h"
#include "GenerateAuthDataApiImpl.h"

#include "SMFSmfRegistrationApiImpl.h"
#include "AMFRegistrationFor3GPPAccessApiImpl.h"


#include "udm_app.hpp"

//using namespace oai::udm_server::api;
// using namespace oai::udm::api;
using namespace oai::udm::app;

using namespace oai::udm::api;
using namespace config;
using namespace org::openapitools::server::api;


class UDMApiServer {
 public:
  UDMApiServer(Pistache::Address address, udm_app* udm_app_inst)
      : m_httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(address)) {
    m_router  = std::make_shared<Pistache::Rest::Router>();
    m_address = address.host() + ":" + (address.port()).toString();

/*
    m_defaultApiImpl =
        std::make_shared<DefaultApiImpl>(m_router, udm_app_inst, m_address);
    m_authenticationResultDeletionApiImpl =
        std::make_shared<AuthenticationResultDeletionApiImpl>(
            m_router, udm_app_inst, m_address);
  */
  }
  void init(size_t thr = 1);
  void start();
  void shutdown();

 private:
  std::shared_ptr<Pistache::Http::Endpoint> m_httpEndpoint;
  std::shared_ptr<Pistache::Rest::Router> m_router;


  std::shared_ptr<AccessAndMobilitySubscriptionDataRetrievalApiImpl> m_accessAndMobilitySubscriptionDataRetrievalApiImpl;
  std::shared_ptr<GPSIToSUPITranslationApiImpl>
      m_gPSIToSUPITranslationApiImpl;

  std::shared_ptr<GroupIdentifiersApiImpl>
      m_groupIdentifiersApiImpl;

  std::shared_ptr<ProvidingAcknowledgementOfSteeringOfRoamingApiImpl>
      m_providingAcknowledgementOfSteeringOfRoamingApiImpl;

  std::shared_ptr<ProvidingAcknowledgementOfUEParametersUpdateApiImpl>
      m_providingAcknowledgementOfUEParametersUpdateApiImpl;

  std::shared_ptr<RetrievalOfMultipleDataSetsApiImpl>
      m_retrievalOfMultipleDataSetsApiImpl;

  std::shared_ptr<RetrievalOfSharedDataApiImpl>
      m_retrievalOfSharedDataApiImpl;


  std::shared_ptr<SMFSelectionSubscriptionDataRetrievalApiImpl>
      m_sMFSelectionSubscriptionDataRetrievalApiImpl;

  std::shared_ptr<SMSManagementSubscriptionDataRetrievalApiImpl>
      m_sMSManagementSubscriptionDataRetrievalApiImpl;

  std::shared_ptr<SMSSubscriptionDataRetrievalApiImpl>
      m_sMSSubscriptionDataRetrievalApiImpl;

  std::shared_ptr<SessionManagementSubscriptionDataRetrievalApiImpl>
      m_sessionManagementSubscriptionDataRetrievalApiImpl;

  std::shared_ptr<SliceSelectionSubscriptionDataRetrievalApiImpl>
      m_sliceSelectionSubscriptionDataRetrievalApiImpl;

  std::shared_ptr<SubscriptionCreationApiImpl>
      m_subscriptionCreationApiImpl;

  std::shared_ptr<SubscriptionCreationForSharedDataApiImpl>
      m_subscriptionCreationForSharedDataApiImpl;

  std::shared_ptr<SubscriptionDeletionApiImpl>
      m_subscriptionDeletionApiImpl;

  std::shared_ptr<SubscriptionDeletionForSharedDataApiImpl>
      m_subscriptionDeletionForSharedDataApiImpl;
  std::shared_ptr<SubscriptionModificationApiImpl>
      m_subscriptionModificationApiImpl;


  std::shared_ptr<TraceConfigurationDataRetrievalApiImpl>
      m_traceConfigurationDataRetrievalApiImpl;

  std::shared_ptr<UEContextInSMFDataRetrievalApiImpl>
      m_uEContextInSMFDataRetrievalApiImpl;
  std::shared_ptr<UEContextInSMSFDataRetrievalApiImpl>
      m_uEContextInSMSFDataRetrievalApiImpl;


  std::shared_ptr<ConfirmAuthApiImpl>
      m_confirmAuthApiImpl;

  std::shared_ptr<DeleteAuthApiImpl>
      m_deleteAuthApiImpl;
  std::shared_ptr<GenerateAuthDataApiImpl>
      m_generateAuthDataApiImpl;


  std::shared_ptr<SMFSmfRegistrationApiImpl>
      m_sMFSmfRegistrationApiImpl;

  std::shared_ptr<AMFRegistrationFor3GPPAccessApiImpl>
      m_aMFRegistrationFor3GPPAccessApiImpl;





  std::string m_address;
};

#endif
