/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IPSMGWRegistrationApi.h
 *
 * 
 */

#ifndef IPSMGWRegistrationApi_H_
#define IPSMGWRegistrationApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "IpSmGwRegistration.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  IPSMGWRegistrationApi {
public:
    IPSMGWRegistrationApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~IPSMGWRegistrationApi() {}
    void init();

    const std::string base = "/nudm-uecm/v1";

private:
    void setupRoutes();

    void ip_sm_gw_registration_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void ipsmgw_registration_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Register an IP-SM-GW
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">Identifier of the UE</param>
    /// <param name="ipSmGwRegistration"></param>
    virtual void ip_sm_gw_registration(const std::string &ueId, const IpSmGwRegistration &ipSmGwRegistration, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* IPSMGWRegistrationApi_H_ */

