/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SMSF3GPPAccessRegistrationInfoRetrievalApi.h
 *
 * 
 */

#ifndef SMSF3GPPAccessRegistrationInfoRetrievalApi_H_
#define SMSF3GPPAccessRegistrationInfoRetrievalApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "ProblemDetails.h"
#include "SmsfRegistration.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  SMSF3GPPAccessRegistrationInfoRetrievalApi {
public:
    SMSF3GPPAccessRegistrationInfoRetrievalApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~SMSF3GPPAccessRegistrationInfoRetrievalApi() {}
    void init();

    const std::string base = "/nudm-uecm/v1";

private:
    void setupRoutes();

    void get3_gpp_smsf_registration_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void smsf3_gpp_access_registration_info_retrieval_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// retrieve the SMSF registration for 3GPP access information
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">Identifier of the UE</param>
    /// <param name="supportedFeatures"> (optional, default to &quot;&quot;)</param>
    virtual void get3_gpp_smsf_registration(const std::string &ueId, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* SMSF3GPPAccessRegistrationInfoRetrievalApi_H_ */

