/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SMSFRegistrationFor3GPPAccessApi.h
 *
 * 
 */

#ifndef SMSFRegistrationFor3GPPAccessApi_H_
#define SMSFRegistrationFor3GPPAccessApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "ProblemDetails.h"
#include "SmsfRegistration.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  SMSFRegistrationFor3GPPAccessApi {
public:
    SMSFRegistrationFor3GPPAccessApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~SMSFRegistrationFor3GPPAccessApi() {}
    void init();

    const std::string base = "/nudm-uecm/v1";

private:
    void setupRoutes();

    void 3_gpp_smsf_registration_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void smsf_registration_for3_gpp_access_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// register as SMSF for 3GPP access
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">Identifier of the UE</param>
    /// <param name="smsfRegistration"></param>
    virtual void 3_gpp_smsf_registration(const std::string &ueId, const SmsfRegistration &smsfRegistration, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* SMSFRegistrationFor3GPPAccessApi_H_ */

