/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TriggerPCSCFRestorationApi.h
 *
 * 
 */

#ifndef TriggerPCSCFRestorationApi_H_
#define TriggerPCSCFRestorationApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "ProblemDetails.h"
#include "TriggerRequest.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  TriggerPCSCFRestorationApi {
public:
    TriggerPCSCFRestorationApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~TriggerPCSCFRestorationApi() {}
    void init();

    const std::string base = "/nudm-uecm/v1";

private:
    void setupRoutes();

    void trigger_pcscf_restoration_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void trigger_pcscf_restoration_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Trigger the Restoration of the P-CSCF
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="triggerRequest"></param>
    virtual void trigger_pcscf_restoration(const TriggerRequest &triggerRequest, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* TriggerPCSCFRestorationApi_H_ */

