/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UELocationInformationRetrievalApi.h
 *
 * 
 */

#ifndef UELocationInformationRetrievalApi_H_
#define UELocationInformationRetrievalApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "LocationInfo.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  UELocationInformationRetrievalApi {
public:
    UELocationInformationRetrievalApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~UELocationInformationRetrievalApi() {}
    void init();

    const std::string base = "/nudm-uecm/v1";

private:
    void setupRoutes();

    void get_location_info_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void ue_location_information_retrieval_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// retrieve the target UE&#39;s location information
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">Identifier of the UE</param>
    /// <param name="supportedFeatures"> (optional, default to &quot;&quot;)</param>
    virtual void get_location_info(const std::string &ueId, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* UELocationInformationRetrievalApi_H_ */

