/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AMF3GppAccessRegistrationInfoRetrievalApi.h
 *
 *
 */

#ifndef AMF3GppAccessRegistrationInfoRetrievalApi_H_
#define AMF3GppAccessRegistrationInfoRetrievalApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "Amf3GppAccessRegistration.h"
#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;

class AMF3GppAccessRegistrationInfoRetrievalApi {
 public:
  AMF3GppAccessRegistrationInfoRetrievalApi(
      std::shared_ptr<Pistache::Rest::Router>);
  virtual ~AMF3GppAccessRegistrationInfoRetrievalApi() {}
  void init();

 private:
  void setupRoutes();

  void get3_gpp_registration_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void amf3_gpp_access_registration_info_retrieval_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// retrieve the AMF registration for 3GPP access information
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="ueId">Identifier of the UE</param>
  /// <param name="supportedFeatures"> (optional, default to
  /// &quot;&quot;)</param>
  virtual void get3_gpp_registration(
      const std::string& ueId,
      const Pistache::Optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif /* AMF3GppAccessRegistrationInfoRetrievalApi_H_ */
