/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * CreateEESubscriptionApi.h
 *
 *
 */

#ifndef CreateEESubscriptionApi_H_
#define CreateEESubscriptionApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "CreatedEeSubscription.h"
#include "EeSubscription.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::udm::api {

class CreateEESubscriptionApi {
 public:
  explicit CreateEESubscriptionApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~CreateEESubscriptionApi() = default;
  void init();

 private:
  void setupRoutes();

  void create_ee_subscription_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void create_ee_subscription_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Subscribe
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="ueIdentity">Represents the scope of the UE for which the
  /// subscription is applied. Contains the GPSI of the user or the external
  /// group ID or any UE.</param> <param name="eeSubscription"></param>
  virtual void create_ee_subscription(
      const std::string& ueIdentity,
      const oai::model::udm::EeSubscription& eeSubscription,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::udm::api

#endif /* CreateEESubscriptionApi_H_ */
