/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DeleteAuthApi.h
 *
 *
 */

#ifndef DeleteAuthApi_H_
#define DeleteAuthApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "AuthEvent.h"
#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;

class DeleteAuthApi {
 public:
  DeleteAuthApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~DeleteAuthApi() {}
  void init();

  const std::string base = "/nudm-ueau/";

 private:
  void setupRoutes();

  void delete_auth_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void delete_auth_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Deletes the authentication result in the UDM
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supi">SUPI of the user</param>
  /// <param name="authEventId">authEvent Id</param>
  /// <param name="authEvent"></param>
  virtual void delete_auth(
      const std::string& supi, const std::string& authEventId,
      const AuthEvent& authEvent, Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif /* DeleteAuthApi_H_ */
