/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IPSMGWDeregistrationApi.h
 *
 *
 */

#ifndef IPSMGWDeregistrationApi_H_
#define IPSMGWDeregistrationApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "ProblemDetails.h"

namespace oai::udm::api {

class IPSMGWDeregistrationApi {
 public:
  IPSMGWDeregistrationApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~IPSMGWDeregistrationApi() {}
  void init();

 private:
  void setupRoutes();

  void ip_sm_gw_deregistration_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void ipsmgw_deregistration_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Delete the IP-SM-GW registration
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="ueId">Identifier of the UE</param>
  virtual void ip_sm_gw_deregistration(
      const std::string& ueId, Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::udm::api

#endif /* IPSMGWDeregistrationApi_H_ */
