/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IPSMGWRegistrationInfoRetrievalApi.h
 *
 *
 */

#ifndef IPSMGWRegistrationInfoRetrievalApi_H_
#define IPSMGWRegistrationInfoRetrievalApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "IpSmGwRegistration.h"
#include "ProblemDetails.h"

namespace oai::udm::api {

using namespace oai::model::udm;
class IPSMGWRegistrationInfoRetrievalApi {
 public:
  IPSMGWRegistrationInfoRetrievalApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~IPSMGWRegistrationInfoRetrievalApi() {}
  void init();

 private:
  void setupRoutes();

  void get_ip_sm_gw_registration_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void ipsmgw_registration_info_retrieval_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Retrieve the IP-SM-GW registration information
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="ueId">Identifier of the UE</param>
  virtual void get_ip_sm_gw_registration(
      const std::string& ueId, Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::udm::api

#endif /* IPSMGWRegistrationInfoRetrievalApi_H_ */
