/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ProvidingAcknowledgementOfUEParametersUpdateApi.h
 *
 *
 */

#ifndef ProvidingAcknowledgementOfUEParametersUpdateApi_H_
#define ProvidingAcknowledgementOfUEParametersUpdateApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "AcknowledgeInfo.h"
#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

using namespace oai::model::udm;

class ProvidingAcknowledgementOfUEParametersUpdateApi {
 public:
  ProvidingAcknowledgementOfUEParametersUpdateApi(
      std::shared_ptr<Pistache::Rest::Router>);
  virtual ~ProvidingAcknowledgementOfUEParametersUpdateApi() {}
  void init();

 private:
  void setupRoutes();

  void upu_ack_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void providing_acknowledgement_of_ue_parameters_update_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Nudm_Sdm Info for UPU service operation
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supi">Identifier of the UE</param>
  /// <param name="acknowledgeInfo"> (optional)</param>
  virtual void upu_ack(
      const std::string& supi, const AcknowledgeInfo& acknowledgeInfo,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif /* ProvidingAcknowledgementOfUEParametersUpdateApi_H_ */
