/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SMSFDeregistrationFor3GPPAccessApi.h
 *
 *
 */

#ifndef SMSFDeregistrationFor3GPPAccessApi_H_
#define SMSFDeregistrationFor3GPPAccessApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

class SMSFDeregistrationFor3GPPAccessApi {
 public:
  SMSFDeregistrationFor3GPPAccessApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~SMSFDeregistrationFor3GPPAccessApi() {}
  void init();

 private:
  void setupRoutes();

  void _3_gpp_smsf_deregistration_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void smsf_deregistration_for3_gpp_access_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// delete the SMSF registration for 3GPP access
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="ueId">Identifier of the UE</param>
  /// <param name="smsfSetId"> (optional, default to &quot;&quot;)</param>
  virtual void _3_gpp_smsf_deregistration(
      const std::string& ueId, const Pistache::Optional<std::string>& smsfSetId,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif /* SMSFDeregistrationFor3GPPAccessApi_H_ */
