/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SubscriptionDeletionApi.h
 *
 *
 */

#ifndef SubscriptionDeletionApi_H_
#define SubscriptionDeletionApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include <string>

#include "ProblemDetails.h"

namespace oai {
namespace udm {
namespace api {

// using namespace oai::model::udm;

class SubscriptionDeletionApi {
 public:
  SubscriptionDeletionApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~SubscriptionDeletionApi() {}
  void init();

 private:
  void setupRoutes();

  void unsubscribe_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void subscription_deletion_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// unsubscribe from notifications
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supi">SUPI of the user</param>
  /// <param name="subscriptionId">Id of the SDM Subscription</param>
  virtual void unsubscribe(
      const std::string& supi, const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace api
}  // namespace udm
}  // namespace oai

#endif /* SubscriptionDeletionApi_H_ */
