/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TriggerAMFFor3GPPAccessDeregistrationApi.h
 *
 * 
 */

#ifndef TriggerAMFFor3GPPAccessDeregistrationApi_H_
#define TriggerAMFFor3GPPAccessDeregistrationApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "AmfDeregInfo.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  TriggerAMFFor3GPPAccessDeregistrationApi {
public:
    TriggerAMFFor3GPPAccessDeregistrationApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~TriggerAMFFor3GPPAccessDeregistrationApi() {}
    void init();

    const std::string base = "/nudm-uecm/v1";

private:
    void setupRoutes();

    void dereg_amf_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void trigger_amf_for3_gpp_access_deregistration_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// trigger AMF for 3GPP access deregistration
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueId">Identifier of the UE</param>
    /// <param name="amfDeregInfo"></param>
    virtual void dereg_amf(const std::string &ueId, const AmfDeregInfo &amfDeregInfo, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* TriggerAMFFor3GPPAccessDeregistrationApi_H_ */

