/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UECMRegistrationInfoRetrievalApi.h
 *
 *
 */

#ifndef UECMRegistrationInfoRetrievalApi_H_
#define UECMRegistrationInfoRetrievalApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <optional>
#include <pistache/router.h>

#include "ProblemDetails.h"
#include "RegistrationDataSetName.h"
#include "RegistrationDataSets.h"
// #include "Set.h"
#include <string>

#include "Snssai.h"

namespace oai::udm::api {

using namespace oai::_3gpp::model;

class UECMRegistrationInfoRetrievalApi {
 public:
  UECMRegistrationInfoRetrievalApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~UECMRegistrationInfoRetrievalApi() {}
  void init();

 private:
  void setupRoutes();

  void get_registrations_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void uecm_registration_info_retrieval_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// retrieve UE registration data sets
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="ueId">Identifier of the UE</param>
  /// <param name="registrationDatasetNames">List of UECM registration dataset
  /// names</param> <param name="supportedFeatures"> (optional, default to
  /// &quot;&quot;)</param> <param name="singleNssai"> (optional, default to
  /// Snssai())</param> <param name="dnn"> (optional, default to
  /// &quot;&quot;)</param>
  // virtual void get_registrations(const std::string &ueId, const
  // std::optional<Set<RegistrationDataSetName>> &registrationDatasetNames,
  // const std::optional<std::string> &supportedFeatures, const
  // std::optional<Snssai> &singleNssai, const
  // std::optional<std::string> &dnn, Pistache::Http::ResponseWriter
  // &response) = 0;
};

}  // namespace oai::udm::api

#endif /* UECMRegistrationInfoRetrievalApi_H_ */
