/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AuthEvent.h
 *
 *
 */

#ifndef AuthEvent_H_
#define AuthEvent_H_

#include "AuthType.h"
#include <nlohmann/json.hpp>
#include <string>

namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class AuthEvent {
public:
  AuthEvent();
  virtual ~AuthEvent();

  void validate();

  /////////////////////////////////////////////
  /// AuthEvent members

  /// <summary>
  ///
  /// </summary>
  std::string getNfInstanceId() const;
  void setNfInstanceId(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  bool isSuccess() const;
  void setSuccess(bool const value);
  /// <summary>
  ///
  /// </summary>
  std::string getTimeStamp() const;
  void setTimeStamp(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getAuthType() const;
  void setAuthType(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getServingNetworkName() const;
  void setServingNetworkName(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  bool isAuthRemovalInd() const;
  void setAuthRemovalInd(bool const value);
  bool authRemovalIndIsSet() const;
  void unsetAuthRemovalInd();

  friend void to_json(nlohmann::json &j, const AuthEvent &o);
  friend void from_json(const nlohmann::json &j, AuthEvent &o);

protected:
  std::string m_NfInstanceId;

  bool m_Success;

  std::string m_TimeStamp;

  std::string m_AuthType;

  std::string m_ServingNetworkName;

  bool m_AuthRemovalInd;
  bool m_AuthRemovalIndIsSet;
};

} // namespace model
} // namespace udm
} // namespace oai

#endif /* AuthEvent_H_ */
