/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AuthenticationInfoResult.h
 *
 *
 */

#ifndef AuthenticationInfoResult_H_
#define AuthenticationInfoResult_H_

#include <nlohmann/json.hpp>
#include <string>

#include "AuthType.h"
#include "AuthenticationVector.h"

namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class AuthenticationInfoResult {
 public:
  AuthenticationInfoResult();
  virtual ~AuthenticationInfoResult();

  void validate();

  /////////////////////////////////////////////
  /// AuthenticationInfoResult members

  /// <summary>
  ///
  /// </summary>
  AuthType getAuthType() const;
  void setAuthType(AuthType const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();
  /// <summary>
  ///
  /// </summary>
  AuthenticationVector getAuthenticationVector() const;
  void setAuthenticationVector(AuthenticationVector const& value);
  bool authenticationVectorIsSet() const;
  void unsetAuthenticationVector();
  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const& value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  bool isAkmaInd() const;
  void setAkmaInd(bool const value);
  bool akmaIndIsSet() const;
  void unsetAkmaInd();

  friend void to_json(nlohmann::json& j, const AuthenticationInfoResult& o);
  friend void from_json(const nlohmann::json& j, AuthenticationInfoResult& o);

 protected:
  AuthType m_AuthType;

  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
  AuthenticationVector m_AuthenticationVector;
  bool m_AuthenticationVectorIsSet;
  std::string m_Supi;
  bool m_SupiIsSet;
  bool m_AkmaInd;
  bool m_AkmaIndIsSet;
};

}  // namespace model
}  // namespace udm
}  // namespace oai

#endif /* AuthenticationInfoResult_H_ */
