/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AvEpsAka.h
 *
 *
 */

#ifndef AvEpsAka_H_
#define AvEpsAka_H_

#include "HssAvType.h"
#include <nlohmann/json.hpp>
#include <string>

namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class AvEpsAka {
public:
  AvEpsAka();
  virtual ~AvEpsAka();

  void validate();

  /////////////////////////////////////////////
  /// AvEpsAka members

  /// <summary>
  ///
  /// </summary>
  HssAvType getAvType() const;
  void setAvType(HssAvType const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getRand() const;
  void setRand(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getXres() const;
  void setXres(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getAutn() const;
  void setAutn(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getKasme() const;
  void setKasme(std::string const &value);

  friend void to_json(nlohmann::json &j, const AvEpsAka &o);
  friend void from_json(const nlohmann::json &j, AvEpsAka &o);

protected:
  HssAvType m_AvType;

  std::string m_Rand;

  std::string m_Xres;

  std::string m_Autn;

  std::string m_Kasme;
};

} // namespace model
} // namespace udm
} // namespace oai

#endif /* AvEpsAka_H_ */
