/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AvType.h
 *
 *
 */

#ifndef AvType_H_
#define AvType_H_

#include <nlohmann/json.hpp>

namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class AvType {
public:
  AvType();
  virtual ~AvType();

  void validate();

  /////////////////////////////////////////////
  /// AvType members

  friend void to_json(nlohmann::json &j, const AvType &o);
  friend void from_json(const nlohmann::json &j, AvType &o);

protected:
};

} // namespace model
} // namespace udm
} // namespace oai

#endif /* AvType_H_ */
