/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "CnType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::udm::model {

CnType::CnType() {}

void CnType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::udm::helpers::ValidationException(msg.str());
  }
}

bool CnType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool CnType::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "CnType" : pathPrefix;

  return success;
}

bool CnType::operator==(const CnType& rhs) const {
  return true;
}

bool CnType::operator!=(const CnType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CnType& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, CnType& o) {}

}  // namespace oai::udm::model
