/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DeregistrationReason.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

DeregistrationReason::DeregistrationReason() {}

DeregistrationReason::~DeregistrationReason() {}

void DeregistrationReason::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const DeregistrationReason& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, DeregistrationReason& o) {}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
