/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * EeSubscription.h
 *
 *
 */

#ifndef EeSubscription_H_
#define EeSubscription_H_

#include "MonitoringConfiguration.h"
#include "ContextInfo.h"
#include <string>
#include "ReportingOptions.h"
#include <map>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class EeSubscription {
 public:
  EeSubscription();
  virtual ~EeSubscription() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const EeSubscription& rhs) const;
  bool operator!=(const EeSubscription& rhs) const;

  /////////////////////////////////////////////
  /// EeSubscription members

  /// <summary>
  ///
  /// </summary>
  std::string getCallbackReference() const;
  void setCallbackReference(std::string const& value);
  /// <summary>
  /// A map (list of key-value pairs where ReferenceId serves as key) of
  /// MonitoringConfigurations
  /// </summary>
  std::map<std::string, MonitoringConfiguration> getMonitoringConfigurations()
      const;
  void setMonitoringConfigurations(
      std::map<std::string, MonitoringConfiguration> const& value);
  /// <summary>
  ///
  /// </summary>
  ReportingOptions getReportingOptions() const;
  void setReportingOptions(ReportingOptions const& value);
  bool reportingOptionsIsSet() const;
  void unsetReportingOptions();
  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();
  /// <summary>
  ///
  /// </summary>
  std::string getSubscriptionId() const;
  void setSubscriptionId(std::string const& value);
  bool subscriptionIdIsSet() const;
  void unsetSubscriptionId();
  /// <summary>
  ///
  /// </summary>
  ContextInfo getContextInfo() const;
  void setContextInfo(ContextInfo const& value);
  bool contextInfoIsSet() const;
  void unsetContextInfo();
  /// <summary>
  ///
  /// </summary>
  bool isEpcAppliedInd() const;
  void setEpcAppliedInd(bool const value);
  bool epcAppliedIndIsSet() const;
  void unsetEpcAppliedInd();
  /// <summary>
  ///
  /// </summary>
  std::string getScefDiamHost() const;
  void setScefDiamHost(std::string const& value);
  bool scefDiamHostIsSet() const;
  void unsetScefDiamHost();
  /// <summary>
  ///
  /// </summary>
  std::string getScefDiamRealm() const;
  void setScefDiamRealm(std::string const& value);
  bool scefDiamRealmIsSet() const;
  void unsetScefDiamRealm();
  /// <summary>
  ///
  /// </summary>
  std::string getNotifyCorrelationId() const;
  void setNotifyCorrelationId(std::string const& value);
  bool notifyCorrelationIdIsSet() const;
  void unsetNotifyCorrelationId();
  /// <summary>
  ///
  /// </summary>
  std::string getSecondCallbackRef() const;
  void setSecondCallbackRef(std::string const& value);
  bool secondCallbackRefIsSet() const;
  void unsetSecondCallbackRef();

  friend void to_json(nlohmann::json& j, const EeSubscription& o);
  friend void from_json(const nlohmann::json& j, EeSubscription& o);

 protected:
  std::string m_CallbackReference;

  std::map<std::string, MonitoringConfiguration> m_MonitoringConfigurations;

  ReportingOptions m_ReportingOptions;
  bool m_ReportingOptionsIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
  std::string m_SubscriptionId;
  bool m_SubscriptionIdIsSet;
  ContextInfo m_ContextInfo;
  bool m_ContextInfoIsSet;
  bool m_EpcAppliedInd;
  bool m_EpcAppliedIndIsSet;
  std::string m_ScefDiamHost;
  bool m_ScefDiamHostIsSet;
  std::string m_ScefDiamRealm;
  bool m_ScefDiamRealmIsSet;
  std::string m_NotifyCorrelationId;
  bool m_NotifyCorrelationIdIsSet;
  std::string m_SecondCallbackRef;
  bool m_SecondCallbackRefIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* EeSubscription_H_ */
