/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EventReportMode.h"
#include "Helpers.h"

#include <sstream>

namespace oai::udm::model {

EventReportMode::EventReportMode() {}

void EventReportMode::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::udm::helpers::ValidationException(msg.str());
  }
}

bool EventReportMode::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EventReportMode::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EventReportMode" : pathPrefix;

  return success;
}

bool EventReportMode::operator==(const EventReportMode& rhs) const {
  return true;
}

bool EventReportMode::operator!=(const EventReportMode& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EventReportMode& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, EventReportMode& o) {}

}  // namespace oai::udm::model
