/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * HssAuthenticationInfoResult.h
 *
 *
 */

#ifndef HssAuthenticationInfoResult_H_
#define HssAuthenticationInfoResult_H_

#include <nlohmann/json.hpp>
#include <string>

#include "HssAuthenticationVectors.h"

namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class HssAuthenticationInfoResult {
 public:
  HssAuthenticationInfoResult();
  virtual ~HssAuthenticationInfoResult();

  void validate();

  /////////////////////////////////////////////
  /// HssAuthenticationInfoResult members

  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();
  /// <summary>
  ///
  /// </summary>
  HssAuthenticationVectors getHssAuthenticationVectors() const;
  void setHssAuthenticationVectors(HssAuthenticationVectors const& value);

  friend void to_json(nlohmann::json& j, const HssAuthenticationInfoResult& o);
  friend void from_json(
      const nlohmann::json& j, HssAuthenticationInfoResult& o);

 protected:
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
  HssAuthenticationVectors m_HssAuthenticationVectors;
};

}  // namespace model
}  // namespace udm
}  // namespace oai

#endif /* HssAuthenticationInfoResult_H_ */
