/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "HssAuthType.h"

namespace oai {
namespace udm {
namespace model {

HssAuthType::HssAuthType() {}

HssAuthType::~HssAuthType() {}

void HssAuthType::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const HssAuthType &o) { j = nlohmann::json(); }

void from_json(const nlohmann::json &j, HssAuthType &o) {}

} // namespace model
} // namespace udm
} // namespace oai
