/**
 * Nudm_UEAU
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "HssAuthTypeInUri.h"

namespace oai {
namespace udm {
namespace model {

HssAuthTypeInUri::HssAuthTypeInUri() {}

HssAuthTypeInUri::~HssAuthTypeInUri() {}

void HssAuthTypeInUri::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const HssAuthTypeInUri& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, HssAuthTypeInUri& o) {}

}  // namespace model
}  // namespace udm
}  // namespace oai
