/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LocationAccuracy_anyOf.h
 *
 *
 */

#ifndef LocationAccuracy_anyOf_H_
#define LocationAccuracy_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class LocationAccuracy_anyOf {
 public:
  LocationAccuracy_anyOf();
  virtual ~LocationAccuracy_anyOf() = default;

  enum class eLocationAccuracy_anyOf {
    // To have a valid default value.
    // Avoiding nameclashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    CELL_LEVEL,
    RAN_NODE_LEVEL,
    TA_LEVEL,
    N3IWF_LEVEL,
    UE_IP,
    UE_PORT
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const LocationAccuracy_anyOf& rhs) const;
  bool operator!=(const LocationAccuracy_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// LocationAccuracy_anyOf members

  LocationAccuracy_anyOf::eLocationAccuracy_anyOf getValue() const;
  void setValue(LocationAccuracy_anyOf::eLocationAccuracy_anyOf value);

  friend void to_json(nlohmann::json& j, const LocationAccuracy_anyOf& o);
  friend void from_json(const nlohmann::json& j, LocationAccuracy_anyOf& o);

 protected:
  LocationAccuracy_anyOf::eLocationAccuracy_anyOf m_value =
      LocationAccuracy_anyOf::eLocationAccuracy_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* LocationAccuracy_anyOf_H_ */
