/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NotificationFlag.h
 *
 * Possible values are - ACTIVATE: The event notification is activated. -
 * DEACTIVATE: The event notification is deactivated and shall be muted. The
 * available event(s) shall be stored. - RETRIEVAL: The event notification shall
 * be sent to the NF service consumer(s), after that, is muted again.
 */

#ifndef NotificationFlag_H_
#define NotificationFlag_H_

#include "NotificationFlag_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
/// Possible values are - ACTIVATE: The event notification is activated. -
/// DEACTIVATE: The event notification is deactivated and shall be muted. The
/// available event(s) shall be stored. - RETRIEVAL: The event notification
/// shall be sent to the NF service consumer(s), after that, is muted again.
/// </summary>
class NotificationFlag {
 public:
  NotificationFlag();
  virtual ~NotificationFlag() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const NotificationFlag& rhs) const;
  bool operator!=(const NotificationFlag& rhs) const;

  /////////////////////////////////////////////
  /// NotificationFlag members

  friend void to_json(nlohmann::json& j, const NotificationFlag& o);
  friend void from_json(const nlohmann::json& j, NotificationFlag& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* NotificationFlag_H_ */
