/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NotifyItem.h
 *
 *
 */

#ifndef NotifyItem_H_
#define NotifyItem_H_

#include "ChangeItem.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class NotifyItem {
public:
  NotifyItem();
  virtual ~NotifyItem();

  void validate();

  /////////////////////////////////////////////
  /// NotifyItem members

  /// <summary>
  ///
  /// </summary>
  std::string getResourceId() const;
  void setResourceId(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::vector<ChangeItem> &getChanges();

  friend void to_json(nlohmann::json &j, const NotifyItem &o);
  friend void from_json(const nlohmann::json &j, NotifyItem &o);

protected:
  std::string m_ResourceId;

  std::vector<ChangeItem> m_Changes;
};

} // namespace model
} // namespace udm
} // namespace oai

#endif /* NotifyItem_H_ */
