/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PatchResult.h
 *
 *
 */

#ifndef PatchResult_H_
#define PatchResult_H_

#include <nlohmann/json.hpp>
#include <vector>

#include "ReportItem.h"

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class PatchResult {
 public:
  PatchResult();
  virtual ~PatchResult();

  void validate();

  /////////////////////////////////////////////
  /// PatchResult members

  /// <summary>
  ///
  /// </summary>
  std::vector<ReportItem>& getReport();
  void setReport(std::vector<ReportItem> const& value);

  friend void to_json(nlohmann::json& j, const PatchResult& o);
  friend void from_json(const nlohmann::json& j, PatchResult& o);

 protected:
  std::vector<ReportItem> m_Report;
};

}  // namespace oai::udm::model

#endif /* PatchResult_H_ */
