/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PgwInfo.h
 *
 *
 */

#ifndef PgwInfo_H_
#define PgwInfo_H_

#include <nlohmann/json.hpp>
#include <string>

#include "PlmnId.h"
using namespace org::openapitools::server::model;
namespace oai {
namespace udm {
namespace model {

/// <summary>
///
/// </summary>
class PgwInfo {
 public:
  PgwInfo();
  virtual ~PgwInfo();

  void validate();

  /////////////////////////////////////////////
  /// PgwInfo members

  /// <summary>
  ///
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getPgwFqdn() const;
  void setPgwFqdn(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  PlmnId getPlmnId() const;
  void setPlmnId(PlmnId const& value);
  bool plmnIdIsSet() const;
  void unsetPlmnId();

  friend void to_json(nlohmann::json& j, const PgwInfo& o);
  friend void from_json(const nlohmann::json& j, PgwInfo& o);

 protected:
  std::string m_Dnn;

  std::string m_PgwFqdn;

  PlmnId m_PlmnId;
  bool m_PlmnIdIsSet;
};

}  // namespace model
}  // namespace udm
}  // namespace oai

#endif /* PgwInfo_H_ */
