/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReachabilityReport.h
 *
 *
 */

#ifndef ReachabilityReport_H_
#define ReachabilityReport_H_

#include <vector>
#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class ReachabilityReport {
 public:
  ReachabilityReport();
  virtual ~ReachabilityReport() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const ReachabilityReport& rhs) const;
  bool operator!=(const ReachabilityReport& rhs) const;

  /////////////////////////////////////////////
  /// ReachabilityReport members

  /// <summary>
  ///
  /// </summary>
  std::string getAmfInstanceId() const;
  void setAmfInstanceId(std::string const& value);
  bool amfInstanceIdIsSet() const;
  void unsetAmfInstanceId();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getAccessTypeList() const;
  void setAccessTypeList(std::vector<std::string> const& value);
  bool accessTypeListIsSet() const;
  void unsetAccessTypeList();
  /// <summary>
  ///
  /// </summary>
  std::string getReachability() const;
  void setReachability(std::string const& value);
  bool reachabilityIsSet() const;
  void unsetReachability();
  /// <summary>
  ///
  /// </summary>
  std::string getMaxAvailabilityTime() const;
  void setMaxAvailabilityTime(std::string const& value);
  bool maxAvailabilityTimeIsSet() const;
  void unsetMaxAvailabilityTime();

  friend void to_json(nlohmann::json& j, const ReachabilityReport& o);
  friend void from_json(const nlohmann::json& j, ReachabilityReport& o);

 protected:
  std::string m_AmfInstanceId;
  bool m_AmfInstanceIdIsSet;
  std::vector<std::string> m_AccessTypeList;
  bool m_AccessTypeListIsSet;
  std::string m_Reachability;
  bool m_ReachabilityIsSet;
  std::string m_MaxAvailabilityTime;
  bool m_MaxAvailabilityTimeIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* ReachabilityReport_H_ */
