/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReachabilityForSmsConfiguration.h
 *
 *
 */

#ifndef ReachabilityForSmsConfiguration_H_
#define ReachabilityForSmsConfiguration_H_

#include "ReachabilityForSmsConfiguration_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class ReachabilityForSmsConfiguration {
 public:
  ReachabilityForSmsConfiguration();
  virtual ~ReachabilityForSmsConfiguration() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const ReachabilityForSmsConfiguration& rhs) const;
  bool operator!=(const ReachabilityForSmsConfiguration& rhs) const;

  /////////////////////////////////////////////
  /// ReachabilityForSmsConfiguration members

  friend void to_json(
      nlohmann::json& j, const ReachabilityForSmsConfiguration& o);
  friend void from_json(
      const nlohmann::json& j, ReachabilityForSmsConfiguration& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* ReachabilityForSmsConfiguration_H_ */
