/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ReachabilityForDataConfiguration.h"
#include "Helpers.h"

#include <sstream>

namespace oai::udm::model {

ReachabilityForDataConfiguration::ReachabilityForDataConfiguration() {}

void ReachabilityForDataConfiguration::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::udm::helpers::ValidationException(msg.str());
  }
}

bool ReachabilityForDataConfiguration::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ReachabilityForDataConfiguration::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ReachabilityForDataConfiguration" : pathPrefix;

  return success;
}

bool ReachabilityForDataConfiguration::operator==(
    const ReachabilityForDataConfiguration& rhs) const {
  return

      (getReportCfg() == rhs.getReportCfg())

          ;
}

bool ReachabilityForDataConfiguration::operator!=(
    const ReachabilityForDataConfiguration& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ReachabilityForDataConfiguration& o) {
  j              = nlohmann::json();
  j["reportCfg"] = o.m_ReportCfg;
}

void from_json(const nlohmann::json& j, ReachabilityForDataConfiguration& o) {
  j.at("reportCfg").get_to(o.m_ReportCfg);
}

ReachabilityForDataReportConfig ReachabilityForDataConfiguration::getReportCfg()
    const {
  return m_ReportCfg;
}
void ReachabilityForDataConfiguration::setReportCfg(
    ReachabilityForDataReportConfig const& value) {
  m_ReportCfg = value;
}

}  // namespace oai::udm::model
