/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReachabilityForDataReportConfig.h
 *
 *
 */

#ifndef ReachabilityForDataReportConfig_H_
#define ReachabilityForDataReportConfig_H_

#include "ReachabilityForDataReportConfig_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class ReachabilityForDataReportConfig {
 public:
  ReachabilityForDataReportConfig();
  virtual ~ReachabilityForDataReportConfig() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const ReachabilityForDataReportConfig& rhs) const;
  bool operator!=(const ReachabilityForDataReportConfig& rhs) const;

  /////////////////////////////////////////////
  /// ReachabilityForDataReportConfig members

  friend void to_json(
      nlohmann::json& j, const ReachabilityForDataReportConfig& o);
  friend void from_json(
      const nlohmann::json& j, ReachabilityForDataReportConfig& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* ReachabilityForDataReportConfig_H_ */
