/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RegistrationDataSets.h
 *
 * 
 */

#ifndef RegistrationDataSets_H_
#define RegistrationDataSets_H_


#include "AmfNon3GppAccessRegistration.h"
#include "SmfRegistrationInfo.h"
#include "Amf3GppAccessRegistration.h"
#include "SmsfRegistration.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RegistrationDataSets
{
public:
    RegistrationDataSets();
    virtual ~RegistrationDataSets();

    void validate();

    /////////////////////////////////////////////
    /// RegistrationDataSets members

    /// <summary>
    /// 
    /// </summary>
    Amf3GppAccessRegistration getAmf3Gpp() const;
    void setAmf3Gpp(Amf3GppAccessRegistration const& value);
    bool amf3GppIsSet() const;
    void unsetAmf3Gpp();
    /// <summary>
    /// 
    /// </summary>
    AmfNon3GppAccessRegistration getAmfNon3Gpp() const;
    void setAmfNon3Gpp(AmfNon3GppAccessRegistration const& value);
    bool amfNon3GppIsSet() const;
    void unsetAmfNon3Gpp();
    /// <summary>
    /// 
    /// </summary>
    SmfRegistrationInfo getSmfRegistration() const;
    void setSmfRegistration(SmfRegistrationInfo const& value);
    bool smfRegistrationIsSet() const;
    void unsetSmfRegistration();
    /// <summary>
    /// 
    /// </summary>
    SmsfRegistration getSmsf3Gpp() const;
    void setSmsf3Gpp(SmsfRegistration const& value);
    bool smsf3GppIsSet() const;
    void unsetSmsf3Gpp();
    /// <summary>
    /// 
    /// </summary>
    SmsfRegistration getSmsfNon3Gpp() const;
    void setSmsfNon3Gpp(SmsfRegistration const& value);
    bool smsfNon3GppIsSet() const;
    void unsetSmsfNon3Gpp();

    friend void to_json(nlohmann::json& j, const RegistrationDataSets& o);
    friend void from_json(const nlohmann::json& j, RegistrationDataSets& o);
protected:
    Amf3GppAccessRegistration m_Amf3Gpp;
    bool m_Amf3GppIsSet;
    AmfNon3GppAccessRegistration m_AmfNon3Gpp;
    bool m_AmfNon3GppIsSet;
    SmfRegistrationInfo m_SmfRegistration;
    bool m_SmfRegistrationIsSet;
    SmsfRegistration m_Smsf3Gpp;
    bool m_Smsf3GppIsSet;
    SmsfRegistration m_SmsfNon3Gpp;
    bool m_SmsfNon3GppIsSet;
};

}
}
}
}

#endif /* RegistrationDataSets_H_ */
