/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ReportItem.h"

namespace oai::udm::model {

ReportItem::ReportItem() { m_Path = ""; }

ReportItem::~ReportItem() {}

void ReportItem::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ReportItem& o) {
  j = nlohmann::json();
  j["path"] = o.m_Path;
}

void from_json(const nlohmann::json& j, ReportItem& o) {
  j.at("path").get_to(o.m_Path);
}

std::string ReportItem::getPath() const { return m_Path; }
void ReportItem::setPath(std::string const& value) { m_Path = value; }

}  // namespace oai::udm::model
