/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RevokedCause.h
 *
 *
 */

#ifndef RevokedCause_H_
#define RevokedCause_H_

#include "RevokedCause_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::udm::model {

/// <summary>
///
/// </summary>
class RevokedCause {
 public:
  RevokedCause();
  virtual ~RevokedCause() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const RevokedCause& rhs) const;
  bool operator!=(const RevokedCause& rhs) const;

  /////////////////////////////////////////////
  /// RevokedCause members

  friend void to_json(nlohmann::json& j, const RevokedCause& o);
  friend void from_json(const nlohmann::json& j, RevokedCause& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::udm::model

#endif /* RevokedCause_H_ */
