/**
 * Nudm_UECM
 * Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmfRegistrationInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SmfRegistrationInfo::SmfRegistrationInfo() {}

SmfRegistrationInfo::~SmfRegistrationInfo() {}

void SmfRegistrationInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SmfRegistrationInfo& o) {
  j                        = nlohmann::json();
  j["smfRegistrationList"] = o.m_SmfRegistrationList;
}

void from_json(const nlohmann::json& j, SmfRegistrationInfo& o) {
  j.at("smfRegistrationList").get_to(o.m_SmfRegistrationList);
}

std::vector<SmfRegistration>& SmfRegistrationInfo::getSmfRegistrationList() {
  return m_SmfRegistrationList;
}
void SmfRegistrationInfo::setSmfRegistrationList(
    std::vector<SmfRegistration> const& value) {
  m_SmfRegistrationList = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
