/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "RetrievalOfSharedDataApi.h"
#include "Helpers.h"

namespace oai {
namespace udm {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace oai::udm::model;

RetrievalOfSharedDataApi::RetrievalOfSharedDataApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
}

void RetrievalOfSharedDataApi::init() {
    setupRoutes();
}

void RetrievalOfSharedDataApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(*router, base + "/shared-data", Routes::bind(&RetrievalOfSharedDataApi::get_shared_data_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&RetrievalOfSharedDataApi::retrieval_of_shared_data_api_default_handler, this));
}

void RetrievalOfSharedDataApi::get_shared_data_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the query params
    auto sharedDataIdsQuery = request.query().get("shared-data-ids");
    Pistache::Optional<std::vector<std::string>> sharedDataIds;
    if(!sharedDataIdsQuery.isEmpty()){
        std::vector<std::string> value;
        if(fromStringValue(sharedDataIdsQuery.get(), value)){
            sharedDataIds = Pistache::Some(value);
        }
    }
    auto supportedFeaturesQuery = request.query().get("supportedFeatures");
    Pistache::Optional<std::string> supportedFeatures;
    if(!supportedFeaturesQuery.isEmpty()){
        std::string value;
        if(fromStringValue(supportedFeaturesQuery.get(), value)){
            supportedFeatures = Pistache::Some(value);
        }
    }
    
    // Getting the header params
    auto ifNoneMatch = request.headers().tryGetRaw("If-None-Match");
    auto ifModifiedSince = request.headers().tryGetRaw("If-Modified-Since");

    try {
      this->get_shared_data(sharedDataIds, supportedFeatures, ifNoneMatch, ifModifiedSince, response);
    } catch (nlohmann::detail::exception &e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    } catch (std::exception &e) {
        //send a 500 error
        response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
        return;
    }

}

void RetrievalOfSharedDataApi::retrieval_of_shared_data_api_default_handler(const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}

