/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscriptionCreationApi.h
 *
 * 
 */

#ifndef SubscriptionCreationApi_H_
#define SubscriptionCreationApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "ProblemDetails.h"
#include "SdmSubscription.h"
#include <string>

namespace oai {
namespace udm {
namespace api {

using namespace oai::udm::model;

class  SubscriptionCreationApi {
public:
    SubscriptionCreationApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~SubscriptionCreationApi() {}
    void init();

    const std::string base = "/nudm-sdm/v2";

private:
    void setupRoutes();

    void subscribe_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void subscription_creation_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// subscribe to notifications
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supi">SUPI of the user</param>
    /// <param name="sdmSubscription"></param>
    virtual void subscribe(const std::string &supi, const SdmSubscription &sdmSubscription, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}

#endif /* SubscriptionCreationApi_H_ */

